openapi: 3.0.0
info:
  title: Media Upload API
  version: 1.0.0
  description: API for uploading media files.

paths:
  /api/v1/media/upload:
    post:
      summary: Upload media files
      description: Upload multiple media files.
      tags:
        - Media
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photos:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '200':
          description: Successful upload
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: No files uploaded
        '401':
          description: Unauthorized

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
